---
# NodePort: Exposes the Service on each Node's IP at a static port.
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  namespace: default
  labels:
    app: "neto15_4"
    component: mysql
spec:
  type: NodePort
  selector:
    app: "neto15_4"
    component: mysql
  ports:
    - name: phpmyadmin-nodeport
      protocol: TCP
      nodePort: 30000 # Port to apply from outside (to see ips - 'kubectl get nodes -o wide').
      port: 80 # Port to apply from inside (to see ips - 'kubectl get svc').
