---
apiVersion: v1
kind: Config
users:
  - name: $ACCOUNT_NAME
    user:
      token: $TOKEN
clusters:
  - cluster:
      certificate-authority-data: $CERTIFICATE_AUTHORITY_DATA
      server: $SERVER_URL
    name: $CLUSTER_NAME
contexts:
  - context:
      cluster: $CLUSTER_NAME
      user: $ACCOUNT_NAME
    name: $CLUSTER_NAME-$ACCOUNT_NAME-context
current-context: $CLUSTER_NAME-$ACCOUNT_NAME-context
