---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: infra-sec
  name: petya-read-exec-pods-svc-ing-rolebinding
subjects:
  - kind: User
    name: system:serviceaccount:infra-sec:petya # Service account to bind role to. Case-sensitive!
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # Role or ClusterRole
  name: read-exec-pods-svc-ing # Role to bind to service account.
  apiGroup: rbac.authorization.k8s.io
