---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: infra-sec
  name: read-exec-pods-svc-ing-global
rules:
  - apiGroups: [ "" ]
    resources: [ pods, pods/log, services, persistentvolumeclaims ]
    verbs: [ get, list, watch, describe ]
  - apiGroups: [ "" ]
    resources: [ pods/exec ]
    verbs: [ create ]
  - apiGroups: [ extensions ]
    resources: [ ingresses ]
    verbs: [ get, list, watch ]
