---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: $NAMESPACE
  name: $ACCOUNT_NAME-$ROLENAME-rolebinding
subjects:
  - kind: User
    name: system:serviceaccount:$NAMESPACE:$ACCOUNT_NAME # Service account to bind role to. Case-sensitive!
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # Role or ClusterRole
  name: $ROLENAME # Role to bind to service account.
  apiGroup: rbac.authorization.k8s.io
