---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-1
  labels:
    nsName: ns-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hworld-1
  namespace: ns-1
  labels:
    app: hworld-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hworld-1 # Must match own metadata.labels.app
  template:
    metadata:
      labels:
        app: hworld-1
    spec:
      containers:
        - name: hworld-1
          image: olezhuravlev/hello-world:1.1.0
          ports:
            - name: hw-port-1
              containerPort: 80
              protocol: TCP
---
# NodePort: Exposes the Service on each Node's IP at a static port.
apiVersion: v1
kind: Service
metadata:
  name: hw-svc-1
  namespace: ns-1
  labels:
    app: hworld-1
spec:
  type: NodePort
  selector:
    app: hworld-1 # Must match own metadata.labels.app
  ports:
    - name: hw-svc-port-1
      protocol: TCP
      nodePort: 30001 # Port to apply from outside (to see ips - 'kubectl get nodes -o wide').
      port: 8081 # Port to apply from inside (to see ips - 'kubectl get svc').
      targetPort: hw-port-1 # Port to map acces to (to see ips - 'kubectl get pods -o wide')
