---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-2
  labels:
    nsName: ns-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hworld-2
  namespace: ns-1
  labels:
    app: hworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hworld-2 # Must match own metadata.labels.app
  template:
    metadata:
      labels:
        app: hworld-2
    spec:
      containers:
        - name: hworld-2
          image: olezhuravlev/hello-world:1.2.0
          ports:
            - name: hw-port-2
              containerPort: 80
              protocol: TCP
---
# NodePort: Exposes the Service on each Node's IP at a static port.
apiVersion: v1
kind: Service
metadata:
  name: hw-svc-2
  namespace: ns-1
  labels:
    app: hworld-2
spec:
  type: NodePort
  selector:
    app: hworld-2 # Must match own metadata.labels.app
  ports:
    - name: hw-svc-port-2
      protocol: TCP
      nodePort: 30002 # Port to apply from outside (to see ips - 'kubectl get nodes -o wide').
      port: 8082 # Port to apply from inside (to see ips - 'kubectl get svc').
      targetPort: hw-port-2 # Port to map acces to (to see ips - 'kubectl get pods -o wide')
