---
# NodePort: Exposes the Service on each Node's IP at a static port.
apiVersion: v1
kind: Service
metadata:
  name: vault-nodeport
  labels:
    app: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
    - name: vault-nodeport
      protocol: TCP
      nodePort: 31000 # Port to apply from outside (to see ips - 'kubectl get nodes -o wide').
      port: 8200 # Port to apply from inside (to see ips - 'kubectl get svc').
      targetPort: vault-http # Port to map acces to (to see ips - 'kubectl get pods -o wide')