---
apiVersion: v1
kind: Pod
metadata:
  name: vault-test
spec:
  containers:
  - name: vault-test
    image: olezhuravlev/vault_test:1.0.0
    env:
    - name: url
      value: "http://10.200.166.190:8200"
    - name: token
      value: "aiphohTaa0eeHei"
    - name: write
      value: "true"
  restartPolicy: Never
