---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  labels:
    app: vault
data:
  vault.hcl: |
    disable_mlock = true
    ui = true
    api_addr = "http://vault:8200"

    listener "tcp" {
      address = "[::]:8200"
      tls_disable = 1
      #tls_cert_file = "/vault/userconfig/tls-server/server.crt"
      #tls_key_file = "/vault/userconfig/tls-server/server.key"
      #tls_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
    }
    storage "file" {
      path = "/vault/data"
    }
---
# Non TLS Version for learning only, do not use in production mode
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  labels:
    app: vault
spec:
  serviceName: "vault"
  selector:
    matchLabels:
      app: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:1.9.0
          imagePullPolicy: IfNotPresent
          args:
            - "server"
            - "-config=/etc/vault/config/vault.hcl"
          ports:
            - name: vault-http
              containerPort: 8200
              protocol: "TCP"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK # разрешает делать системный вызов mlock без повышения привилегий контейнера, выделение памяти большими страницами
                - CAP_SETFCAP # нужно для мапинга юзер ид0 в нового пользака в неймпейсе ядра, вызов setcap
          volumeMounts:
            - name: config
              mountPath: /etc/vault/config
            - name: vault-data
              mountPath: /vault/data
      volumes:
        - name: config
          configMap:
            name: vault-config
  volumeClaimTemplates:
    - metadata:
        name: vault-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: nfs
        resources:
          requests:
            storage: 1Gi
---
# NodePort: Exposes the Service on each Node's IP at a static port.
apiVersion: v1
kind: Service
metadata:
  name: vault-nodeport
  labels:
    app: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
    - name: vault-nodeport
      protocol: TCP
      nodePort: 31000 # Port to apply from outside (to see ips - 'kubectl get nodes -o wide').
      port: 8200 # Port to apply from inside (to see ips - 'kubectl get svc').
      targetPort: vault-http # Port to map acces to (to see ips - 'kubectl get pods -o wide')
